### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by jchannon** [publichealthengland/coronavirus-dashboard-api-net-sdk#12]
What are your thoughts on releasing CI packages eg.on every master branch build it releases it to somewhere like Feedz or only to Nuget on a release?

Any ETA on when you want the first version released to NuGet?

**Comment by xenatisch** [comment]
Sure, we can do Feedz on master builds and Nuget on releases. 

Re the ETA for the first version, my first opportunity would probably be on Wednesday. I'm expecting tomorrow to be wayyy to full. Sorry, it's just been a bit ... well, let's say busy.

**Comment by jchannon** [comment]
No problem at alI, I can imagine. If you need any help elsewhere that I can
help with let me know

**Comment by jchannon** [comment]
I created a Feedz org under my name, not sure if that's ok if you want want one under PHE. I have a token that needs to be added to Github secrets so the GH Actions can push the to nuget feed on CI but I don't have access to add that.

**Comment by xenatisch** [comment]
I think it has to be under PHE... for the time being at least! 

I'll create an account later this evening. Needs to be connected to <covid19-tech@phe.gov.uk>. 

We could also create a release for Nuget if you think everything is ready. The token is set on GitHub, so all we need to do is to create a release here.

**Comment by jchannon** [comment]
Cool.

I think the code is aligned with the other languages so I think we could do
a release if you’re happy

**Comment by jchannon** [comment]
Also worth noting you could use feedz for the JavaScript repo if you wanted

**Comment by xenatisch** [comment]
Well, I'm doing that with GitHub packages for JS. Thinking of it, we could actually do that with NuGet too... any thoughts on that?

**Comment by jchannon** [comment]
Yeah, unfortunately the nuget support under the github package repo is not
good.  The feed is private so people can't access the packages and to
remove packages you have to contact github support and they will only
remove old packages if its a GDPR issue. I'm sure in time they will change
this but at the mo it's pretty pointless
